CREATE TABLE transactions (
    id VARCHAR2(32) DEFAULT SYS_GUID() PRIMARY KEY,
    amount NUMBER(15, 2) NOT NULL,
    currency VARCHAR2(3) NOT NULL,
    status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    risk_score VARCHAR2(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);